/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mouseclicker;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author smyrnof
 */
public class LinuxJFrame extends MainJFrame {    

    /**
     * Creates new form LinuxJFrame
     */
    public LinuxJFrame() {
        initComponents();
        BtnHotkeySet.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                BtnHotkeySetMouseClicked(evt);
            }
        });        
        btnStartMacro.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                btnStartMacroMouseClicked(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void BtnHotkeySetMouseClicked(java.awt.event.MouseEvent evt) {
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("mouseclicker/Bundle");
        if(cbHotkeyFirst.getSelectedItem().toString().equals(cbHotkeySecond.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(LinuxJFrame.this,bundle.getString("SetHotkeyError"),bundle.getString("Error"),JOptionPane.ERROR_MESSAGE);
        }else{
            //TODO:
        }
    }    
    
    public void btnStartMacroMouseClicked(java.awt.event.MouseEvent evt) {             
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("mouseclicker/Bundle");
        if (!threadislive){
            BtnHotkeySetMouseClicked(evt);
            mt = new MacroThread();
            mt.start();
            threadislive=true;
            btnStartMacro.setBackground(Color.red);
            btnStartMacro.setText("Makroyu Durdur");
            this.setState(MainJFrame.ICONIFIED);            
        }else {
            mt.interrupt();
            threadislive=false;
            btnStartMacro.setBackground(Color.green);
            btnStartMacro.setText("Makroyu Başlat");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinuxJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinuxJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinuxJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinuxJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinuxJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
